domain:
  name: dev.local.home

frontend:
  uri: http://dev.local.home:3000

spring:
  cloud:
    aws:
      s3:
        endpoint: http://s3:9000
        path-style-access-enabled: true
      region:
        static: us-east-1
      credentials: 
        access-key: ${MINIO_ROOT_USER}
        secret-key: ${MINIO_ROOT_PASSWORD}